# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import netscan.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', netscan.utils.fields.MACAddressField(max_length=17)),
                ('ssid', models.CharField(blank=True, max_length=200, null=True)),
                ('channel', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
